### PR TITLE
DCK-13: Add WebForm and Wrapper Teasers

### PR DESCRIPTION
**Pull request by ivan-berezhnov**
## Issue

> **Updated DB with demo content**
> **Created Contact US and Wrapper Teaser paragraphs**
> **Added style for Camp tickets**
> **Updated style for mail layout**
> **Moved to here basic payment and fixed build warnings**

## Steps for review:

- [ ] go to https://dck-13--dcamp-site.build.drupalcampkyiv.org/
- [ ] verify design for Contact US and Wrapper Teaser paragraphs is correct
- [ ] verify Camp Tickets block appear in home page and has small style.

## General checks
- [ ] All coding styles are fulfilled and there are no any issues reported by CodeSniffer.
- [ ] All tests are running and there are no failed tests reported by CI.
- [ ] Documentation has been updated according to PR changes.
- [ ] Steps for review have been provided according to PR changes.

Thank you for your сontribution and help to Drupal Ukraine!

### CODE REVIEW

**Comment by ivan-berezhnov** [comment]
Hi @andypost 
Please review my PR. Thx

**Comment by andypost** [comment]
It is not clear what this PR doing from description. why updates mixed with styles?

For example https://github.com/drupal-ukraine/dcamp-site/commit/e6eb0cdef579b539e413a8c6e069264a8893e81f it updates database or styles?

Btw some files missing new line at the end...

PS: is there any demo instance cos I'm not using docsal

**Comment by ivan-berezhnov** [comment]
> It is not clear what this PR doing from description. why updates mixed with styles?
> 
> For example [e6eb0cd](https://github.com/drupal-ukraine/dcamp-site/commit/e6eb0cdef579b539e413a8c6e069264a8893e81f) it updates database or styles?
> 
> Btw some files missing new line at the end...
> 
> PS: is there any demo instance cos I'm not using docsal

Hi @andypost 
Sorry, I did this PR in the night and asked you but wanted to  ask Anatoliy Polyakov.

Also, I added description to PR and now we are working on initialization project, add some main blocks.
The DB here because we don't have production site.

If don't use Docksal you can take db and files in docroot (before run composer install).

**Comment by ivan-berezhnov** [comment]
Hi @anpolimus 
Please review my PR. Thx

**Comment by anpolimus** [comment]
What we need to fix here:
- [ ] Rename webform to English. We have to configure everything on English first and then translate.
- [ ] We have to simplify commerce payment workflow - there are more steps than we need.
We could merge checkout/login and checkout screens together like we done at IFW.
- [ ] we need to remove address field from checkout - it is not needed (I need to investigate how to do it).
- [ ] we need to remove address field input somehow
- [ ] we have to add facebook login link to the login screen.

**Pull request merged**
